export const SITE = {
  APP_NAME: "APP_NAME",
  COMPANY_NAME: "COMPANY_NAME",
  YOURDOMAIN: "YOURDOMAIN.com",
  SUPPORT_EMAIL: "support@YOURDOMAIN.com",
  ONE_LINE_PITCH: "ONE_LINE_PITCH",
  EFFECTIVE_DATE: "MONTH DAY, YEAR",
  GOVERNING_LAW: "GOVERNING_LAW"
} as const;

